[shell]
zsh_indicator = ""
format = "[$indicator]($style)"
disabled = false

[python]
disabled = false

[container]
symbol = "ğŸ‹"
format = "[$symbol]($style)"

[env_var.COLCON_PREFIX_PATH]
format = "[ env! ](yellow bold)"
# format = "[ colcon ğŸ’© ](yellow bold)"

[git_status]
disabled = true
